# NumPy

In [1]:
pip install numpy

In [3]:
pip list

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [1]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Sap\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.14.0               |   py39haa95532_0         937 KB
    ------------------------------------------------------------
                                           Total:         937 KB

The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 4.14.0-py39haa95532_0




conda-4.14.0         | 937 KB    |            |   0% 
conda-4.14.0         | 937 KB    | 1          |   2% 
conda-4.14.0         | 937 KB    | #          |  10% 
conda-4.14.0         | 937 KB    | ##3        |  24% 
conda-4.14.0         | 937 KB    | ###5       |  36% 
conda-4.14.0         | 937 KB    | ######6    |  67% 
conda-4.14.0         | 937 KB    | ########## | 100% 
con

#### Import and declare library

In [14]:
import numpy as np


##### version of Library 

In [20]:
print(np.__version__)

1.21.5


####  Array

In [21]:
# single Array
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# 2-D Array
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
# type of Array
print(arr.ndim)

2


In [38]:
# row and colom of array
print(arr.shape)

(2, 4)


In [39]:
print(type(arr))

<class 'numpy.ndarray'>


In [40]:
# memory location of array
print(arr.data)

#### function of NumPy

In [24]:
np.amin(arr)

1

In [25]:
np.amax(arr)

10

In [26]:
np.mean(arr)

5.5

In [27]:
np.median(arr)

5.5

In [28]:
np.ptp(arr)

9

In [29]:
np.std(arr)

2.8722813232690143

In [30]:
np.var(arr)

8.25

In [31]:
np.average(arr)

5.5

In [54]:
np.percentile(arr,10)

1.7000000000000002


# Random number generator using array

In [41]:
from numpy import random

In [51]:
x=random.randint(10)
print(x)

1


In [53]:
x=random.rand()
print(x)

0.615728159802281


In [56]:
x=random.randint(100,size=(5))
print(x)

[64 89 54 52 56]


In [58]:
x=random.randint(100,size=(3,3))
print(x)

[[36 46 54]
 [41 12 17]
 [ 1 47 75]]


In [61]:
x=random.seed(101)
x=random.randint(100,size=(3,5))
print(x)

[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]]


In [65]:
#1-D List
l1=[1,2,3]


#1-D vertical
l2=[[10],
   [20],
   [30]]

vector1=np.array(l1)
vector2=np.array(l2)

print("Horizontal vector")
print(vector1)

print("-------------------------------")

print("Vertical vector")
print(vector2)


Horizontal vector
[1 2 3]
-------------------------------
Vertical vector
[[10]
 [20]
 [30]]


# Creating matrix in numpy

In [66]:
#string input value
a=np.matrix('1 2;3 4')
a

matrix([[1, 2],
        [3, 4]])

In [68]:
#integer value
a=np.matrix([[1,2],[3, 4]])
a

matrix([[1, 2],
        [3, 4]])

# Matrix Multiplication in numpy

In [70]:
A= 5

B=[[6,7],
  [8,9]]
print(np.dot(A,B))

[[30 35]
 [40 45]]


In [74]:
A= [[4,7],
  [8,4]]

B=[[6,7],
  [8,9]]
print(np.dot(A,B))
print("------------------------")
print(np.dot(B,A))

[[80 91]
 [80 92]]
------------------------
[[ 80  70]
 [104  92]]


In [75]:
A=([1,2,3],
  [4,5,6],
  [6,7,8])
print(np.transpose(A))

[[1 4 6]
 [2 5 7]
 [3 6 8]]


# Percentile & Interquartile in Numpy

In [1]:
import numpy as np 

data = [1,2,3,4,5,6,7,8,9,0,11,12,13,14,15,16,17,18,19,20]

#first Quartile(Q1)
Q1 = np.median(data[:10])
print(Q1)

#second Quartile(Q2)
Q2 = np.median(data[10:])
print(Q2)

IQR=Q2-Q1

print(IQR)

4.5
15.5
11.0


# Array Broadcasting in Numpy

In [2]:
a= np.array([1.0,2.0,3.0])
b=np.array([2.0,2.0,2.0])

a*b

array([2., 4., 6.])

In [4]:
a= np.array([1.0,2.0,3.0])
b=2.0

a*b

array([2., 4., 6.])

# Calculate BMI of Cricket Players

In [3]:
import numpy as np
#Height of Players!

hg_in =[61,65,64,69,70,68,64,63,62,66,72]

#convert into numpy array

ht_np = np.array(hg_in)

#convert height from inch to meter by exposing it to 0.0245
ht_np = ht_np*0.0245

print(ht_np)

[1.4945 1.5925 1.568  1.6905 1.715  1.666  1.568  1.5435 1.519  1.617
 1.764 ]


In [4]:
#weight of players in pound
wt_pd=[100,200,160,180,140,155,165,172,180,200,168]

#convert into array
wt_np = np.array(wt_pd)

#convert weight from pound to kg by exposing it to 0.45
wt_np = wt_np*0.45

wt_np

array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 74.25, 77.4 , 81.  ,
       90.  , 75.6 ])

In [5]:
#BMI calculation

BMI =wt_np/(ht_np**2)
BMI

array([20.1474773 , 35.48817184, 29.28467305, 28.3435777 , 21.41964658,
       25.13010006, 30.19981909, 32.48835283, 35.10503991, 34.42091966,
       24.29543246])

In [6]:
BMI[-1]

24.295432458697764

In [7]:
BMI[BMI<21]

array([20.1474773])

In [8]:
BMI[:5]

array([20.1474773 , 35.48817184, 29.28467305, 28.3435777 , 21.41964658])

In [10]:
players =np.array([wt_np,ht_np])
players

array([[45.    , 90.    , 72.    , 81.    , 63.    , 69.75  , 74.25  ,
        77.4   , 81.    , 90.    , 75.6   ],
       [ 1.4945,  1.5925,  1.568 ,  1.6905,  1.715 ,  1.666 ,  1.568 ,
         1.5435,  1.519 ,  1.617 ,  1.764 ]])

In [11]:
players[0][2]

72.0

In [13]:
players[1][2]

1.568

In [14]:
players[1]

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [17]:
#Transpose

pT = players.transpose()

pT

array([[45.    ,  1.4945],
       [90.    ,  1.5925],
       [72.    ,  1.568 ],
       [81.    ,  1.6905],
       [63.    ,  1.715 ],
       [69.75  ,  1.666 ],
       [74.25  ,  1.568 ],
       [77.4   ,  1.5435],
       [81.    ,  1.519 ],
       [90.    ,  1.617 ],
       [75.6   ,  1.764 ]])

In [18]:
pT.shape

(11, 2)

In [22]:
#statical and methematical function on players data

print(np.mean(wt_np))
print(np.median(wt_np))
print(np.sum(wt_np))
print(np.std(wt_np))
print(np.corrcoef(wt_np,ht_np))


74.45454545454545
75.60000000000001
819.0
12.082941667443528
[[1.         0.16451886]
 [0.16451886 1.        ]]


# Area of room task for home work

In [2]:
import numpy as np
# breadth of area
bt_in=[120,110,560,309,234,290,650,205,200,290]

# convert into numpy array
bt_np=np.array(bt_in)
bt_np=bt_np/12
bt_np


array([10.        ,  9.16666667, 46.66666667, 25.75      , 19.5       ,
       24.16666667, 54.16666667, 17.08333333, 16.66666667, 24.16666667])

In [6]:
#lenght of area
ln_in=[420,610,500,209,204,260,250,105,240,290]

#convert into numpy array
ln_np=np.array(ln_in)
ln_np=ln_np/12
ln_np

array([35.        , 50.83333333, 41.66666667, 17.41666667, 17.        ,
       21.66666667, 20.83333333,  8.75      , 20.        , 24.16666667])

In [7]:
#height of area in room
hg_in=[220,120,520,109,224,190,620,225,230,210]

#convert into numpy array
ht_np=np.array(hg_in)

#convert height from inch to foot by exposing 0.0245

ht_np=ht_np/12
ht_np


array([18.33333333, 10.        , 43.33333333,  9.08333333, 18.66666667,
       15.83333333, 51.66666667, 18.75      , 19.16666667, 17.5       ])

In [8]:
#area calculation of room
area=ln_np*ht_np*bt_np
area

array([ 6416.66666667,  4659.72222222, 84259.25925926,  4073.68576389,
        6188.        ,  8290.50925926, 58304.39814815,  2802.734375  ,
        6388.88888889, 10220.48611111])